FROM alpine:3.15
RUN apk add python3 py3-pip py3-setuptools podman shadow shadow-uidmap
RUN adduser worker; usermod -v 10000-42767 -w 10000-42767 worker;
RUN chmod 644 /etc/containers/containers.conf; touch /etc/containers/nodocker
RUN	sed -i  -e 's|^#mount_program|mount_program|g' \
		-e '/additionalimage.*/a "/var/lib/shared",' \
		-e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' \
		/etc/containers/storage.conf; \
	sed -i  -e 's|^unqualified-search-registries[[:space:]]*=.*$|unqualified-search-registries = ["quay.io", "docker.io"]|g' \
		/etc/containers/registries.conf; \
	sed -i  -e 's|^#[[:space:]]remote[[:space:]]*=.*$|remote = true|g' \
		/usr/share/containers/containers.conf /etc/containers/containers.conf;
RUN mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers /var/lib/shared/vfs-images /var/lib/shared/vfs-layers; touch /var/lib/shared/overlay-images/images.lock; touch /var/lib/shared/overlay-layers/layers.lock; touch /var/lib/shared/vfs-images/images.lock; touch /var/lib/shared/vfs-layers/layers.lock; ln -sv /usr/bin/podman /usr/bin/docker

WORKDIR /home/worker/project
RUN mkdir -p /home/worker/.local/share/containers; chown worker:worker -R /home/worker;
USER worker
COPY --chown=worker ./setup* ./
RUN pip install -e '.[test]';
COPY --chown=worker . ./
ENV CONTAINER_HOST="unix:///tmp/podman-run-1000/podman/podman.sock"
ENV DOCKER_HOST="unix:///tmp/podman-run-1000/podman/podman.sock"
