ci:
  autoupdate_schedule: monthly
exclude: "^cibuildwheel/resources/ios-support/(?!make_cross_venv\\.py)"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: (cibuildwheel/resources/pinned_docker_images.cfg)|(.svg$)
  - id: mixed-line-ending
  - id: trailing-whitespace
    exclude: ^cibuildwheel/resources/android/android.patch$

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 321478e58f4938179c6b86e4ddfa923d1547a49b  # frozen: v0.16.6
  hooks:
  - id: ruff-check
    args: ["--fix"]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 7ff8d35ae36a7d2b968f2f90b4c723e292e594ee  # frozen: v2.3.1
  hooks:
  - id: mypy
    name: mypy 3.11 on cibuildwheel/
    args: ["--python-version=3.11"]
    exclude: ^cibuildwheel/resources/android/_cross_venv.py$  # Requires Python 3.13 or later
    additional_dependencies: &mypy-dependencies
      - bracex
      - build
      - dependency-groups>=1.2
      - humanize
      - nox>=2025.2.9
      - packaging
      - pygithub
      - pytest
      - rich
      - tomli_w
      - types-certifi
      - types-click
      - types-jinja2
      - types-pyyaml
      - types-requests
      - types-setuptools
      - uv
      - validate-pyproject
  - id: mypy
    name: mypy 3.14
    args: ["--python-version=3.14"]
    additional_dependencies: *mypy-dependencies

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: a6564f5d57444e123433a5c9af733e3975c77229  # frozen: v0.11.0.1-1
  hooks:
  - id: shellcheck

- repo: local
  hooks:
  - id: disallow-caps
    name: Disallow improper capitalization
    language: pygrep
    entry: PyBind|Numpy|Cmake|Github|PyTest
    types: [markdown]
    exclude: ^docs/working-examples\.md$  # Autogenerated
  - id: cog
    name: Cog the README
    language: python
    pass_filenames: false
    entry: cog -c -P -r -I ./bin README.md
    files: '^(README\.md|docs/changelog\.md|docs/options\.md|bin/readme.*)$'
    additional_dependencies: [cogapp>=3.5]

- repo: https://github.com/henryiii/flake8-lazy
  rev: 3b5e52593dfaec56e6e4a48f237bafcf3d0b83ea  # frozen: v0.9.0
  hooks:
  - id: flake8-lazy
    args: ["--apply=set"]
    files: '^cibuildwheel'
    exclude: "^cibuildwheel/resources/"

- repo: https://github.com/codespell-project/codespell
  rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
  hooks:
  - id: codespell
    args: ["-w"]
    exclude: ^docs/working-examples\.md$  # Autogenerated


- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: c4654a7e007c9619a5eb63c39a456572a0fa1851  # frozen: 0.38.0
  hooks:
    - id: check-dependabot
    - id: check-github-actions
    - id: check-github-workflows
    - id: check-gitlab-ci
    - id: check-readthedocs
    - id: check-jsonschema
      name: Check projects
      args: [--schemafile, docs/data/projects.schema.json]
      files: '^docs/data/projects.yml$'
    - id: check-metaschema
      files: '^docs/data/projects.schema.json$'
