name: cibuildwheel
description: 'Installs and runs cibuildwheel on the current runner'
inputs:
  package-dir:
    description: 'Input directory, defaults to "."'
    required: false
    default: .
  output-dir:
    description: 'Folder to place the outputs in, defaults to "wheelhouse"'
    required: false
    default: wheelhouse
  config-file:
    description: 'File containing the config, defaults to {package}/pyproject.toml'
    required: false
    default: ''
  only:
    description: 'Build a specific wheel only. No need for arch/platform if this is set'
    required: false
    default: ''
branding:
  icon: package
  color: yellow

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      id: python
      with:
        python-version: "3.11 - 3.13"
        update-environment: false

    - id: cibw
      run: |
        # Install cibuildwheel
        "${{ steps.python.outputs.python-path }}" -u << "EOF"
        import os
        import shutil
        import sys
        import venv

        from pathlib import Path
        from subprocess import run


        class EnvBuilder(venv.EnvBuilder):
            def __init__(self):
                super().__init__()

            def setup_scripts(self, context):
                pass

            def post_setup(self, context):
                super().post_setup(context)
                self.bin_path = Path(context.env_exe).parent
                run([sys.executable, "-m", "pip", "--python", context.env_exe, "install", r"${{ github.action_path }}"], check=True)


        print("::group::Install cibuildwheel")
        venv_path = Path(r"${{ runner.temp }}") / "cibw"
        if venv_path.exists():
            shutil.rmtree(venv_path)
        builder = EnvBuilder()
        builder.create(venv_path)
        cibw_path = [path for path in builder.bin_path.glob("cibuildwheel*") if path.stem == "cibuildwheel"][0]
        with open(os.environ["GITHUB_OUTPUT"], "at") as f:
            f.write(f"cibw-path={cibw_path}\n")
        print("::endgroup::")
        EOF
      shell: bash

    # Redirecting stderr to stdout to fix interleaving issue in Actions.
    - run: >
        "${{ steps.cibw.outputs.cibw-path }}"
        "${{ inputs.package-dir }}"
        ${{ inputs.output-dir != ''  && format('--output-dir "{0}"', inputs.output-dir) || ''}}
        ${{ inputs.config-file != '' && format('--config-file "{0}"', inputs.config-file) || ''}}
        ${{ inputs.only != ''        && format('--only "{0}"', inputs.only) || ''}}
        2>&1
      shell: bash
      if: runner.os != 'Windows'

    # Windows needs powershell to interact nicely with Meson
    - run: >
        & "${{ steps.cibw.outputs.cibw-path }}"
        "${{ inputs.package-dir }}"
        ${{ inputs.output-dir != ''  && format('--output-dir "{0}"', inputs.output-dir) || ''}}
        ${{ inputs.config-file != '' && format('--config-file "{0}"', inputs.config-file) || ''}}
        ${{ inputs.only != ''        && format('--only "{0}"', inputs.only) || ''}}
      shell: pwsh
      if: runner.os == 'Windows'
