name: cibuildwheel
description: 'Installs and runs cibuildwheel on the current runner'
inputs:
  package-dir:
    description: 'Input directory, defaults to "."'
    required: false
    default: .
  output-dir:
    description: 'Folder to place the outputs in, defaults to "wheelhouse"'
    required: false
    default: wheelhouse
  archs:
    description: 'Pass a comma separated list of archs to build on. Will activate QEMU emulation.'
    required: false
    default: ''
branding:
  icon: package
  color: yellow

runs:
  using: composite
  steps:

    # This needs powershell-core because github.action path is a Windows-style
    # path on Windows.  Powershell-core understands both types of paths.
    - run: python3 -m pip install ${{ github.action_path }}
      shell: pwsh

    - run: |
        if [[ "$RUNNER_OS" == "Linux" ]] ; then
          archs="${{ inputs.archs }}"
          if [[ "$archs" =~ .*(all|aarch64|ppc64le|s390x).* ]] ; then
            docker run --privileged --rm tonistiigi/binfmt --install all
          fi
        fi
      shell: bash

    - run: python3 -m cibuildwheel ${{ inputs.package-dir }} --output-dir ${{ inputs.output-dir }} --archs "${{ inputs.archs }}"
      shell: bash
