name: cibuildwheel
description: 'Installs and runs cibuildwheel on the current runner'
inputs:
  package-dir:
    description: 'Input directory, defaults to "."'
    required: false
    default: .
  output-dir:
    description: 'Folder to place the outputs in, defaults to "wheelhouse"'
    required: false
    default: wheelhouse
branding:
  icon: package
  color: yellow

runs:
  using: composite
  steps:

    # Use python3 on unix and python on windows. This is
    # only important if a user forgets to run setup-python first.

    # This needs powershell-core because github.action path is a Windows-style
    # path on Windows.  Powershell-core understands both types of paths.
    - run: |
        if ( $RUNNER_OS -eq 'Windows' ) {
            python -m pip install ${{ github.action_path }}
            python -m cibuildwheel ${{ inputs.package-dir }} --output-dir ${{ inputs.output-dir }}
        }
        else {
            python3 -m pip install ${{ github.action_path }}
            python3 -m cibuildwheel ${{ inputs.package-dir }} --output-dir ${{ inputs.output-dir }}
        }
      shell: pwsh
