name: Build

on: [push, pull_request]

jobs:
  build_wheels_macos:
    name: Build wheels on macos-11
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.0
        env:
          CIBW_ARCHS_MACOS: x86_64 arm64

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
