# As written, this configuration will build your wheels on every
# commit, but will only push to PyPI on tagged commits.

os: linux
dist: focal
language: python
python: "3.12"

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco upgrade python -y --version 3.12.4
        - export PATH="/c/Python312:/c/Python312/Scripts:$PATH"
        # make sure it's on PATH as 'python3'
        - ln -s /c/Python312/python.exe /c/Python312/python3.exe

install:
  - python3 -m pip install cibuildwheel==2.21.1

script:
  # build the wheels, put them into './dist'
  - python3 -m cibuildwheel --output-dir dist

deploy:
  provider: pypi
  username: "__token__"
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: "" # Set to an encrypted API token. See https://docs.travis-ci.com/user/deployment/pypi/
