os: linux
dist: focal
language: python
python: "3.12"

jobs:
  include:
    # perform a linux build
    - services: docker
    # perform a linux ARMv8 build
    - services: docker
      arch: arm64
    # perform a linux PPC64LE build
    - services: docker
      arch: ppc64le
    # perform a linux S390X build
    - services: docker
      arch: s390x
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco upgrade python -y --version 3.12.4
        - export PATH="/c/Python312:/c/Python312/Scripts:$PATH"
        # make sure it's on PATH as 'python3'
        - ln -s /c/Python312/python.exe /c/Python312/python3.exe

install:
  - python3 -m pip install cibuildwheel==2.21.1

script:
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse
